<?php

namespace FluentSupport\App\Services;


class TransStrings
{
    public static function getTransStrings()
    {
        return [
            'dashboard_sub_heading' => __('Here are a few tickets you may want to take a look at', 'fluent-support'),
            'dashboard_all_catch_up' => __('Looks like you have caught up everything for now.', 'fluent-support'),
            'Your Overview for Today' => __('Your Overview for Today', 'fluent-support'),
            'Your Business Details' => __('Your Business Details', 'fluent-support'),
            'support_portal_ready' => __('Awesome! Your support portal is ready to go!', 'fluent-support'),
            'Ticket Email Settings' => __('Ticket Email Settings', 'fluent-support'),
            'Business Name' => __('Business Name', 'fluent-support'),
            'Business Email' => __('Business Email', 'fluent-support'),
            'email_can_be_send' => __('Please make sure your website can send emails from this email address', 'fluent-support'),
            'Good' => __('Good', 'fluent-support'),
            'Good Job' => __('Good Job', 'fluent-support'),
            'tickets' => __('tickets', 'fluent-support'),
            'are waiting for reply with' => __('are waiting for reply with', 'fluent-support'),
            'wait time' => __('wait time', 'fluent-support'),
            'max wait time' => __('max wait time', 'fluent-support'),
            'shortcode_auto_page_creation' => __('Create a page automatically with the shortcode', 'fluent-support'),
            'Complete Setup'    => __('Complete Setup', 'fluent-support'),
            'Setup Associate Product/Services for Tickets'    => __('Setup Associate Product/Services for Tickets', 'fluent-support'),
            'Manage Support Staff'    => __('Manage Support Staff', 'fluent-support'),
            'Global Settings'    => __('Global Settings', 'fluent-support'),
            'Go to Dashboard'    => __('Go to Dashboard', 'fluent-support'),
            'Use shortcode'    => __('Use shortcode', 'fluent-support'),
            'in the selected page'    => __('in the selected page', 'fluent-support'),
            'Please setup your support portal first'    => __('Please setup your support portal first', 'fluent-support'),
            'Support Portal Page (For Customers)'    => __('Support Portal Page (For Customers)', 'fluent-support'),
            'eg: Awesome Business Inc'    => __('eg: Awesome Business Inc', 'fluent-support'),
            'From Email Address'    => __('From Email Address', 'fluent-support'),
            'Update Customer'    => __('Update Customer', 'fluent-support'),
            'Create Customer'    => __('Create Customer', 'fluent-support'),
            'Add new customer'    => __('Add new customer', 'fluent-support'),
            'First Name'    => __('First Name', 'fluent-support'),
            'Last Name'    => __('Last Name', 'fluent-support'),
            'Email'    => __('Email', 'fluent-support'),
            'afternoon'    => __('afternoon', 'fluent-support'),
            'evening'    => __('evening', 'fluent-support'),
            'morning'    => __('morning', 'fluent-support'),
            'completed'    => __('completed', 'fluent-support'),
            'All Customers'    => __('All Customers', 'fluent-support'),
            'Add Customer'    => __('Add Customer', 'fluent-support'),
            'Search Customers'    => __('Search Customers', 'fluent-support'),
            'ID'    => __('ID', 'fluent-support'),
            'Name'    => __('Name', 'fluent-support'),
            'Last Activity'    => __('Last Activity', 'fluent-support'),
            'Stats'    => __('Stats', 'fluent-support'),
            'Title'    => __('Title', 'fluent-support'),
            'Status'    => __('Status', 'fluent-support'),
            'Manage'    => __('Manage', 'fluent-support'),
            'Email Subject'    => __('Email Subject', 'fluent-support'),
            'Email Body'    => __('Email Body', 'fluent-support'),
            'enable_email'    => __('Enable This Email Notification', 'fluent-support'),
            'can_not_edit_subject'    => __('You can not edit subject for this email. This subject patern is required for email reply parsing', 'fluent-support'),
            'Save Settings'    => __('Save Settings', 'fluent-support'),
            'Available Smartcodes'    => __('Available Smartcodes', 'fluent-support'),
            'Customer First Name'    => __('Customer First Name', 'fluent-support'),
            'Customer Last Name'    => __('Customer Last Name', 'fluent-support'),
            'Customer Full Name'    => __('Customer Full Name', 'fluent-support'),
            'Customer Email'    => __('Customer Email', 'fluent-support'),
            'Ticket ID'    => __('Ticket ID', 'fluent-support'),
            'Ticket Title'    => __('Ticket Title', 'fluent-support'),
            'Ticket Content'    => __('Ticket Content', 'fluent-support'),
            'Agent First Name'    => __('Agent First Name', 'fluent-support'),
            'Agent Last Name'    => __('Agent Last Name', 'fluent-support'),
            'Agent Full Name'    => __('Agent Full Name', 'fluent-support'),
            'Response Title'    => __('Response Title', 'fluent-support'),
            'Response Content'    => __('Response Content', 'fluent-support'),
            'Business Inboxes'    => __('Business Inboxes', 'fluent-support'),
            'Add New Business Inbox'    => __('Add New Business Inbox', 'fluent-support'),
            'Delete'    => __('Delete', 'fluent-support'),
            'View Settings'    => __('View Settings', 'fluent-support'),
            'Add a New Business Inbox'    => __('Add a New Business Inbox', 'fluent-support'),
            'Inbox Name'    => __('Inbox Name', 'fluent-support'),
            'Support Channel'    => __('Support Channel', 'fluent-support'),
            'Web Based'    => __('Web Based', 'fluent-support'),
            'email'    => __('email', 'fluent-support'),
            'Email Based (MailBox)'    => __('Email Based (MailBox)', 'fluent-support'),
            'Mapped Email'    => __('Mapped Email', 'fluent-support'),
            'mapped_webhook_email'    => __('Please provide mapped webhook email from where you will send emails as webhook', 'fluent-support'),
            'Cancel'    => __('Cancel', 'fluent-support'),
            'Add Business Inbox'    => __('Add Business Inbox', 'fluent-support'),
            'Are You Sure? You can not undo this action.'    => __('Are You Sure? You can not undo this action.', 'fluent-support'),
            'Fallback Business'    => __('Fallback Business', 'fluent-support'),
            'Select related Product/Service'    => __('Select related Product/Service', 'fluent-support'),
            'select_fallback_business'    => __('Please select the fallback business in where the existing tickets will be transferred', 'fluent-support'),
            'Confirm Delete This Business'    => __('Confirm Delete This Business', 'fluent-support'),
            'Please provide fallback box'    => __('Please provide fallback box', 'fluent-support'),
            'Settings'    => __('Settings', 'fluent-support'),
            'Inbox Settings'    => __('Inbox Settings', 'fluent-support'),
            'Email Settings'    => __('Email Settings', 'fluent-support'),
            'admin_get_email'    => __('Please provide the email address where admin will get email if enabled in email settings', 'fluent-support'),
            'Admin Email Address'    => __('Admin Email Address', 'fluent-support'),
            'web'    => __('web', 'fluent-support'),
            'Email Footer For Customers'    => __('Email Footer For Customers', 'fluent-support'),
            'see_available_dynamic_shortcodes'    => __('Click to see Available Dynamic Codes', 'fluent-support'),
            'Ticket Public URL'    => __('Ticket Public URL', 'fluent-support'),
            'Ticket Received Welcome Email'    => __('Ticket Received Welcome Email', 'fluent-support'),
            'Ticket Closed By Agent'    => __('Ticket Closed By Agent', 'fluent-support'),
        ];
    }
}
