import { createApp } from 'vue';
import {
    ElMenu,
    ElMenuItem,
    ElMain,
    ElRow,
    ElCol,
    ElTable,
    ElTableColumn,
    ElPagination,
    ElButtonGroup,
    ElButton,
    ElIcon,

    ElForm,
    ElFormItem,
    ElColorPicker,
    ElInput,
    ElInputNumber,
    ElOption,
    ElOptionGroup,
    ElRadio,
    ElRadioButton,
    ElRadioGroup,
    ElRate,
    ElSelect,
    ElSelectV2,
    ElCheckbox,
    ElCheckboxGroup,

    ElSlider,
    ElSwitch,
    ElTimePicker,
    ElDatePicker,
    ElTimeSelect,
    ElDialog,
    ElSkeleton,
    ElUpload,
    ElTooltip,

    ElTabs,
    ElTabPane,

    ElPopover,
    ElPopconfirm,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElCascader,
    ElCascaderPanel,

    ElTag,

    ElLoading,
    ElMessage,
    ElMessageBox,
    ElNotification
} from 'element-plus';

import {
    Notebook,
    ChatLineSquare,
    User,
    Lightning,
    Refresh,
    Goods,
    OfficeBuilding,
    Service,
    Message,
    ArrowDown,
    ArrowUp,
    EditPen,
    Delete,
    Paperclip,
    Stopwatch,
    Tickets,
    View,
    Plus,
    Flag,
    CaretBottom,
    CaretTop,
    Search,
    Setting,
    Lock,
    CollectionTag,
    Document,
    Cpu,
    AlarmClock,
    Connection,
    InfoFilled,
    CircleCheck,
    UploadFilled,
    Folder,
    ChatLineRound,
    PriceTag,
    Finished
} from '@element-plus/icons-vue/dist/es';

const app = createApp({});

const components = [
    ElMenu,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElMenuItem,
    ElMain,
    ElRow,
    ElCol,
    ElTable,
    ElTableColumn,
    ElPagination,
    ElButtonGroup,
    ElButton,
    ElIcon,
    ElForm,
    ElFormItem,
    ElColorPicker,
    ElInput,
    ElInputNumber,
    ElOption,
    ElOptionGroup,
    ElRadio,
    ElRadioButton,
    ElRadioGroup,
    ElRate,
    ElSelect,
    ElSlider,
    ElSwitch,
    ElTimePicker,
    ElUpload,
    ElTimeSelect,
    ElDialog,
    ElPopover,
    ElSkeleton,
    ElTabs,
    ElTabPane,
    ElTooltip,
    ElCheckbox,
    ElCheckboxGroup,
    ElPopconfirm,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem,
    ElDatePicker,
    ElTag,
    ElSelectV2,
    ElCascader,
    ElCascaderPanel,

    // Icons
    Notebook,
    ChatLineSquare,
    User,
    Lightning,
    Refresh,
    Goods,
    OfficeBuilding,
    Service,
    Message,
    ArrowDown,
    ArrowUp,
    EditPen,
    Delete,
    Paperclip,
    Stopwatch,
    Tickets,
    View,
    Plus,
    Flag,
    CaretBottom,
    CaretTop,
    Search,
    Setting,
    Lock,
    CollectionTag,
    Document,
    Cpu,
    AlarmClock,
    Connection,
    InfoFilled,
    CircleCheck,
    UploadFilled,
    Folder,
    ChatLineRound,
    PriceTag,
    Finished
];

components.forEach(component => {
    app.component(component.name, component)
})

const plugins = [
    ElLoading,
    ElMessage,
    ElMessageBox,
    ElNotification
];

plugins.forEach(plugin => {
    app.use(plugin)
});


export default app;
